import { Link } from 'react-router-dom';
import { useTranslation } from 'react-i18next';

const content = {
  es: {
    title: 'Términos de Servicio',
    s1_title: '1. Membresía al Club',
    s1_desc: 'Al unirte al Club de Lectura Arcana, aceptas que el contenido de la biblioteca es para fines de investigación personal, desarrollo espiritual y estudio académico.',
    s2_title: '2. Uso del Contenido',
    s2_desc: 'Las interacciones con Hermes AI, así como las transcripciones generadas por la narración inteligente, son privadas. El miembro no debe reproducir, distribuir ni comercializar material protegido por derechos de autor que se encuentre dentro del club.',
    s3_title: '3. Suscripción',
    s3_desc: 'La membresía se cobra de manera mensual. El miembro puede cancelar su acceso en cualquier momento, lo cual revocará su capacidad de acceder al contenido al final del ciclo de facturación.',
    s4_title: '4. Propiedad Intelectual',
    s4_desc_1: 'El Club de Lectura Arcana respeta los derechos de propiedad intelectual. Si usted es titular de derechos sobre alguna obra presente en nuestra biblioteca, consulte nuestra ',
    s4_link: 'Política de Derechos de Autor y DMCA',
    s4_desc_2: ' para conocer el procedimiento de reclamo y las opciones de colaboración.'
  },
  en: {
    title: 'Terms of Service',
    s1_title: '1. Club Membership',
    s1_desc: 'By joining the Arcane Reading Club, you agree that library content is for personal research, spiritual development, and academic study purposes.',
    s2_title: '2. Use of Content',
    s2_desc: 'Interactions with Hermes AI, as well as transcripts generated by intelligent narration, are private. Members must not reproduce, distribute, or commercialize copyrighted material found within the club.',
    s3_title: '3. Subscription',
    s3_desc: 'Membership is billed monthly. Members can cancel their access at any time, which will revoke their ability to access content at the end of the billing cycle.',
    s4_title: '4. Intellectual Property',
    s4_desc_1: 'The Arcane Reading Club respects intellectual property rights. If you are a rights holder for any work present in our library, please see our ',
    s4_link: 'Copyright and DMCA Policy',
    s4_desc_2: ' for the claims procedure and collaboration options.'
  }
};

export default function Terms() {
  const { i18n } = useTranslation();
  const lang = i18n.language.startsWith('en') ? 'en' : 'es';
  const text = content[lang];

  return (
    <main className="container" style={{ paddingTop: '8rem', paddingBottom: '4rem', minHeight: '80vh' }}>
      <h1 className="hero-title" style={{ fontSize: '3rem', marginBottom: '2rem' }}>{text.title}</h1>
      
      <div className="glass-panel" style={{ padding: '2rem', borderRadius: 'var(--radius-md)' }}>
        <h2 style={{ color: 'var(--accent-gold)', marginBottom: '1rem', fontFamily: 'var(--font-mystic)' }}>{text.s1_title}</h2>
        <p style={{ marginBottom: '1.5rem', color: 'var(--text-secondary)' }}>
          {text.s1_desc}
        </p>

        <h2 style={{ color: 'var(--accent-gold)', marginBottom: '1rem', fontFamily: 'var(--font-mystic)' }}>{text.s2_title}</h2>
        <p style={{ marginBottom: '1.5rem', color: 'var(--text-secondary)' }}>
          {text.s2_desc}
        </p>

        <h2 style={{ color: 'var(--accent-gold)', marginBottom: '1rem', fontFamily: 'var(--font-mystic)' }}>{text.s3_title}</h2>
        <p style={{ marginBottom: '1.5rem', color: 'var(--text-secondary)' }}>
          {text.s3_desc}
        </p>

        <h2 style={{ color: 'var(--accent-gold)', marginBottom: '1rem', fontFamily: 'var(--font-mystic)' }}>{text.s4_title}</h2>
        <p style={{ marginBottom: '0.5rem', color: 'var(--text-secondary)' }}>
          {text.s4_desc_1}
          <Link to="/derechos-de-autor" style={{ color: 'var(--accent-gold)' }}>{text.s4_link}</Link>
          {text.s4_desc_2}
        </p>
      </div>
    </main>
  );
}
